### ISSUE TITLE
npm run desktop fails with missing meteor-desktop

### ISSUE THREAD

**Issue by rajanski** [clinical-meteor/meteor-on-fhir#146]
The last entry in below fails,
nevertheless the app starts up fine with just the second entry
```

B. Running Local

## Initialize with FHIR test data
INITIALIZE=true Patients=true Practitioners=true meteor

## general development
NODE_ENV=test INITIALIZE=true Patients=true Practitioners=true meteor --settings settings.dev.json

## general development  for desktop app
npm run desktop
```

**Comment by awatson1978** [comment]
This was fixed a few days ago in PR 152.
https://github.com/clinical-meteor/meteor-on-fhir/pull/152

Re-enabled the `meteor-desktop` packages, and updated the readme with more accurate instructions.
