### ISSUE TITLE
Two issues on the homepage for http://clinical.meteorapp.com/

### ISSUE THREAD

**Issue by hugotoledo** [clinical-meteor/meteor-on-fhir#22]
I see two problems with the following sentence on the homepage for http://clinical.meteorapp.com/.

We now offer an HIPAA, FDA, and HL7 eady Interface Engine called Meteor on FHIR.

1) The word "Ready" is missing its first letter.
2) The term HIPAA is typically pronounced as a word rather than spelled, so the article preceding HIPAA should be "a" and not "an".

To be perfectly clear, the sentence should read:

We now offer a HIPAA, FDA, and HL7 Ready Interface Engine called Meteor on FHIR.

I am seeing this in both the latest versions of Chrome and Edge running in Windows 10 Pro (Version 10.0.17134 Build 17134).

(I'd have submitted a pull-request on the page itself but I'm not sure it is maintained or exposed on github.)

**Comment by awatson1978** [comment]
Thanks!  We're getting ready to do some updates to the project websites.  Will hopefully get it in by the end of the month.  :)
