### ISSUE TITLE
Error: Family must be a string

### ISSUE THREAD

**Issue by sushyad** [clinical-meteor/meteor-on-fhir#222]
When setting up the project initially, I am unable to start the server. I get the following error: 

```
W20170411-00:10:03.155(-4)? (STDERR) Error: Family must be a string
W20170411-00:10:03.155(-4)? (STDERR)     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
W20170411-00:10:03.155(-4)? (STDERR)     at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
W20170411-00:10:03.155(-4)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
W20170411-00:10:03.156(-4)? (STDERR)     at packages/clinical_accounts-famous-dead-people.js:420:33
W20170411-00:10:03.156(-4)? (STDERR)     at Array.forEach (native)
W20170411-00:10:03.156(-4)? (STDERR)     at [object Object].Meteor.methods.initializeFamousDeadPeople (packages/clinical_accounts-famous-dead-people.js:403:14)
W20170411-00:10:03.156(-4)? (STDERR)     at packages/check.js:130:16
W20170411-00:10:03.156(-4)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20170411-00:10:03.156(-4)? (STDERR)     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
W20170411-00:10:03.157(-4)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
```

**Comment by awatson1978** [comment]
That's because of the new Patient v3.0.0 schema, which expects `Patient.name.$.family` to be a string, instead of an array.  

Are you using a pre-existing database?  Was the database initialized more than two weeks ago?  You might try `meteor reset` to clear the database of any v.1.0.2 or v.1.6.0 records.  

You could also try downgrading the `clinical:hl7-resource-patient` package.

**Comment by sushyad** [comment]
I'm using the latest development branch and yesterday was the first time
that I downloaded it to set it up, so the database could not be old.

Let me try resetting the database to see if it clears up the error.

**Comment by sushyad** [comment]
After reset I get this:

W20170411-06:34:33.308(-4)? (STDERR) /Users/syadav/.meteor/packages/meteor-tool/.1.4.2_7.1mdmpqf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170411-06:34:33.309(-4)? (STDERR) 						throw(ex);
W20170411-06:34:33.309(-4)? (STDERR) 						^
W20170411-06:34:33.309(-4)? (STDERR)
W20170411-06:34:33.309(-4)? (STDERR) TypeError: Cannot read property 'fhir' of undefined
W20170411-06:34:33.309(-4)? (STDERR)     at meteorInstall.server.metadata.js (server/metadata.js:54:5)
W20170411-06:34:33.309(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170411-06:34:33.309(-4)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170411-06:34:33.310(-4)? (STDERR)     at /Users/syadav/projects/meteor-on-fhir/webapp/.meteor/local/build/programs/server/app/app.js:4637:1
W20170411-06:34:33.310(-4)? (STDERR)     at /Users/syadav/projects/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:295:34
W20170411-06:34:33.310(-4)? (STDERR)     at Array.forEach (native)
W20170411-06:34:33.310(-4)? (STDERR)     at Function._.each._.forEach (/Users/syadav/.meteor/packages/meteor-tool/.1.4.2_7.1mdmpqf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170411-06:34:33.310(-4)? (STDERR)     at /Users/syadav/projects/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:128:5
W20170411-06:34:33.310(-4)? (STDERR)     at /Users/syadav/projects/meteor-on-fhir/webapp/.meteor/local/build/programs/server/boot.js:344:5
W20170411-06:34:33.310(-4)? (STDERR)     at Function.run (/Users/syadav/projects/meteor-on-fhir/webapp/.meteor/local/build/programs/server/profile.js:480:12)

Let me try downgrading the clinical:hl7-resource-patient package.

**Comment by awatson1978** [comment]
That recent error is caused by not having `Meteor.settings` object.  Be sure to use a `settings.*.json` file, like so:

```
meteor --settings settings.dev.json
```

**Comment by sushyad** [comment]
I was able to get it up and running, thanks! I get a warning about the 3x slower performance of bcrypt js implementation, but everything seems to be working otherwise.
