### ISSUE TITLE
Save FHIR resource to IPFS node

### ISSUE THREAD

**Issue by awatson1978** [clinical-meteor/meteor-on-fhir#231]

**Comment by lanzafame** [comment]
@awatson1978 I recently pitched this idea at a Hacking Health event in Brisbane, Australia. I was wondering whether you were thinking of creating native IPFS representation of the FHIR resources (links between resources are links to other IPFS objects) or you were just thinking of using IPFS as a data layer?

**Comment by awatson1978** [comment]
Now that's a fascinating question.  

My initial thought had been to use IPFS to synchronize data dictionaries across the Meteor on FHIR nodes.  So, FHIR Location objects of all the hospitals in the US.  FHIR Organizations of all the healthcare organizations.  Annual ICD, CPT, HCSPC, LOINC, and RXNORM supplemental updates.  That sort of thing.  Data dictionaries that don't include PHI, and which have an authoritative source, and which need to be distributed among many end users.  

To be honest, I hadn't thought about use cases beyond that.

**Comment by awatson1978** [comment]
https://github.com/awatson1978/symptomatic-blockchain-core

**Comment by lanzafame** [comment]
@awatson1978 I cannot access that repo. Maybe it is still set to private?

**Comment by awatson1978** [comment]
Oops.  Sorry, didn't mean to ping you on that.  The repo is private, part of Symptomatic's subscription service.  

We implemented IPFS without any problems, and it's quite obviously doable in either solution... with `references` encoding some sort of database identifier, uri, or IPFS url.  Just have to write a resolver for each.  Will need a HIPAA compliant IPFS network to put PHI resources on it with IPFS references; but non-PHI data should fit fine.  Really just depends on the application.
